In [ ]:
# prompt: numpy

import numpy as np

# Create a numpy array
arr = np.array([1, 2, 3, 4, 5,6,7,8,9])

# Print the array
print(arr)

# Get the shape of the array
print(arr.shape)

# Get the data type of the array
print(arr.dtype)

# Get the size of the array in bytes
print(arr.nbytes)

# Reshape the array
arr = arr.reshape(9, 1)

# Print the reshaped array
print(arr)

# Get the maximum value in the array
print(arr.max())

# Get the minimum value in the array
print(arr.min())

# Get the mean value in the array
print(arr.mean())

# Get the standard deviation of the array
print(arr.std())

# Sum the values in the array
print(arr.sum())


[1 2 3 4 5 6 7 8 9]
(9,)
int64
72
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
9
1
5.0
2.581988897471611
45


In [ ]:
# python program to create
# Empty and Full Numpy arrays

import numpy as np


# Create an 1-D empty array
arr=np.empty(5, dtype=int)
print(arr)




arr[0]=33;
arr[1]=99;
arr[2]=7;
arr[3]=86;
arr[4]=93;


print(arr)

print(arr.size,type(arr))

#user input
for i in range(arr.size):
    n=int(input("enter a number :"))
    arr[i]=n

print(arr)


#creating 1-D array with data
arr2=np.array([77,88,44,33,22])

print(arr2)

#2d empty array
empa = np.empty((3, 4), dtype=int)
print("Empty Array")
print(empa)

# Create a 2D full array
flla = np.full([3, 3], 55, dtype=int)
print("\n Full Array")
print(flla)

arr2d=np.array([[6,6,6],[8,8,8]])
print("create 2d array")
print(arr2d)

temp=[7,16,20,8,5]
arr3=np.array(temp)
print("changing list into array")
print(arr3)

#creating a 3-D array
arr3d=np.array([[[5,9,7,3],[23,23,12,65],[55,99,77,66]]])
print("3-D array")
print(arr3d)
print(arr3d[0,0,0])
print()



l=(x*x for x in range(1,11))
arr4=np.fromiter(l,dtype=int)
print(arr4,type(arr4),arr4.ndim,arr4.size)



arr5=np.copy(arr4)
print(arr5)

print(np.sum(arr5))
print(np.mean(arr5))
print(np.median(arr5))


arr6=np.stack((arr4,arr5),axis=1)
print(arr6)

arr7=np.hstack((arr4,arr5))
print(arr7)
arr8=np.vstack((arr4,arr5))
print(arr8)


arr9=np.array_split(arr4,5)
print(arr9)


#2-D array
a1=np.array([[1,9,7],[9,9,7],[8,5,7]])
b1=np.array([[4,5,6],[7,9,3],[8,6,4]])
print("A1")
print(a1)
print("B1")
print(b1)
sum1=np.add(a1,b1)
print("SUM OF A1 and B1")
print(sum1)
sub1=np.subtract(a1,b1)
print("SUB OF A1 and B1")
print(sub1)
mul1=np.multiply(a1,b1)
print("MULTIPLY OF A1 and B1")
print(mul1)
div1=np.divide(a1,b1)
print("DIVISION OF A1 and B1")
print(div1)
sq1=np.sqrt(a1)
print("SQUARE ROOT of A1")
print(sq1)

In [ ]:
import numpy as np
l=(x*x for x in range(1,11))
arr4=np.fromiter(l,dtype=int)
print(arr4,type(arr4),arr4.ndim,arr4.size)


[  1   4   9  16  25  36  49  64  81 100] <class 'numpy.ndarray'> 1 10


In [ ]:
#creating a 3-D array
import numpy as np
arr3d=np.array([[[5,9,7,3],[239,23,12,65],[55,99,77,66]]])
print("3-D array")
print(arr3d)
print(arr3d[0,1,0])
print()

3-D array
[[[  5   9   7   3]
  [239  23  12  65]
  [ 55  99  77  66]]]
239



In [ ]:
import numpy as np

arr5=np.array([2,3,6,5,5,6,7,8,9,4,5,6,7,8,9,4])
arr5.sort()
print(arr5)
print(np.sum(arr5))
print(np.mean(arr5))
print(np.median(arr5))

[2 3 4 4 5 5 5 6 6 6 7 7 8 8 9 9]
94
5.875
6.0


In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([7,6,5,4,3,9])

arr3=np.stack((arr1,arr2),axis=1)
print(arr3)

arr7=np.hstack((arr1,arr2))
print(arr7)
arr8=np.vstack((arr1,arr2))
print(arr8)

[[1 7]
 [2 6]
 [3 5]
 [4 4]
 [5 3]
 [6 9]]
[1 2 3 4 5 6 7 6 5 4 3 9]
[[1 2 3 4 5 6]
 [7 6 5 4 3 9]]


In [ ]:
arr9=np.array_split(arr5,5)
print(arr9)

[array([2, 3, 4, 4]), array([5, 5, 5]), array([6, 6, 6]), array([7, 7, 8]), array([8, 9, 9])]


In [ ]:
#2-D array
a1=np.array([[1,9,7],[9,9,7],[8,5,7]])
b1=np.array([[4,5,6],[7,9,3],[8,6,4]])
print("A1:")
print(a1)
print("B1:")
print(b1)
sum1=np.add(a1,b1)
print("SUM OF A1 and B1")
print(sum1)
sub1=np.subtract(a1,b1)
print("SUB OF A1 and B1")
print(sub1)
mul1=np.multiply(a1,b1)
print("MULTIPLY OF A1 and B1")
print(mul1)
div1=np.divide(a1,b1)
print("DIVISION OF A1 and B1")
print(div1)
sq1=np.sqrt(a1)
print("SQUARE ROOT of A1")
print(sq1)

A1:
[[1 9 7]
 [9 9 7]
 [8 5 7]]
B1:
[[4 5 6]
 [7 9 3]
 [8 6 4]]
SUM OF A1 and B1
[[ 5 14 13]
 [16 18 10]
 [16 11 11]]
SUB OF A1 and B1
[[-3  4  1]
 [ 2  0  4]
 [ 0 -1  3]]
MULTIPLY OF A1 and B1
[[ 4 45 42]
 [63 81 21]
 [64 30 28]]
DIVISION OF A1 and B1
[[0.25       1.8        1.16666667]
 [1.28571429 1.         2.33333333]
 [1.         0.83333333 1.75      ]]
SQUARE ROOT of A1
[[1.         3.         2.64575131]
 [3.         3.         2.64575131]
 [2.82842712 2.23606798 2.64575131]]


In [ ]:
# prompt: statistics functions
import numpy as np
import statistics as st

arr=np.array([4,5,6,7,4,5,67,8,9,3,4,56,78,9])


# Calculate the mean of the array
mean = np.mean(arr)

# Calculate the median of the array
median = np.median(arr)

# Calculate the mode of the array
mode = st.mode(arr)

# Calculate the standard deviation of the array
std = np.std(arr)

# Calculate the variance of the array
var = np.var(arr)

# Calculate the minimum value in the array
min = np.min(arr)

# Calculate the maximum value in the array
max = np.max(arr)

# Calculate the sum of the array
sum = np.sum(arr)

# Calculate the cumulative sum of the array
cumsum = np.cumsum(arr)

# Calculate the dot product of two arrays
dot_product = np.dot(arr, arr)

# Calculate the cross product of two arrays
cross_product = np.cross(arr, arr)

# Calculate the determinant of a matrix
determinant = np.linalg.det(arr)

# Calculate the inverse of a matrix
inverse = np.linalg.inv(arr)

# Calculate the eigenvalues and eigenvectors of a matrix
eigenvalues, eigenvectors = np.linalg.eig(arr)

# Calculate the singular value decomposition of a matrix
U, s, Vh = np.linalg.svd(arr)

# Calculate the QR decomposition of a matrix
Q, R = np.linalg.qr(arr)

# Calculate the LU decomposition of a matrix
P, L, U = np.linalg.lu(arr1)

# Calculate the Cholesky decomposition of a matrix
L = np.linalg.cholesky(arr)

# Calculate the matrix exponential
matrix_exp = np.linalg.matrix_power(arr, 2)

# Calculate the matrix logarithm
matrix_log = np.linalg.matrix_log(arr)

# Calculate the matrix square root
matrix_sqrt = np.linalg.sqrtm(arr)

# Calculate the matrix power
matrix_power = np.linalg.matrix_power(arr, 3)

# Calculate the matrix norm
matrix_norm = np.linalg.norm(arr)

# Calculate the matrix condition number
matrix_cond = np.linalg.cond(arr)

# Calculate the matrix rank
matrix_rank = np.linalg.matrix_rank(arr)

# Calculate the matrix trace
matrix_trace = np.trace(arr)

# Calculate the matrix determinant
matrix_det = np.linalg.det(arr)

# Calculate the matrix inverse
matrix_inv = np.linalg.inv(arr)

# Calculate the matrix pseudo-inverse
matrix_pinv = np.linalg.pinv(arr)

# Calculate the matrix eigenvalues
matrix_eigvals = np.linalg.eigvals(arr)

# Calculate the matrix eigenvectors
matrix_eigvecs = np.linalg.eigvecs(arr)

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [ ]:
# prompt: numpy statistical methods

# Calculate the variance of the array
print(arr.var())

# Calculate the median of the array
print(np.median(arr))

# Calculate the absolute values of the array
print(np.abs(arr))

# Calculate the cumulative sum of the array
print(np.cumsum(arr))

# Calculate the difference between consecutive elements of the array
print(np.diff(arr))

# Calculate the product of the elements of the array
print(np.prod(arr))

# Calculate the reciprocal of the elements of the array
print(np.reciprocal(arr))

# Calculate the square root of the elements of the array
print(np.sqrt(arr))

# Calculate the exponential of the elements of the array
print(np.exp(arr))

# Calculate the logarithm of the elements of the array
print(np.log(arr))

# Calculate the trigonometric sine of the elements of the array
print(np.sin(arr))


1351.84
86.0
[33 99  7 86 93]
[ 33 132 139 225 318]
[ 66 -92  79   7]
182906262
[0 0 0 0 0]
[5.74456265 9.94987437 2.64575131 9.2736185  9.64365076]
[2.14643580e+14 9.88903032e+42 1.09663316e+03 2.23524660e+37
 2.45124554e+40]
[3.49650756 4.59511985 1.94591015 4.4543473  4.53259949]
[ 0.99991186 -0.99920683  0.6569866  -0.92345845 -0.94828214]


In [ ]:
# prompt: numpy random methods

# Generate a random integer between 0 and 10 (inclusive)
print(np.random.randint(11))

# Generate a random float between 0 and 1 (exclusive)
print(np.random.random())

# Generate a random array of 5 random integers between 0 and 10 (inclusive)
print(np.random.randint(11, size=5))

# Generate a random array of 5 random floats between 0 and 1 (exclusive)
print(np.random.random(5))

# Generate a random array of 5 random integers between 0 and 10 (inclusive) with a specific seed
np.random.seed(123)
print(np.random.randint(11, size=5))

# Generate a random array of 5 random floats between 0 and 1 (exclusive) with a specific seed
np.random.seed(123)
print(np.random.random(5))

# Generate a random array of 5 random integers between 0 and 10 (inclusive) with a specific seed and replace
np.random.seed(123)
print(np.random.choice(11, size=5, replace=True))

# Generate a random array of 5 random integers between 0 and 10 (inclusive) with a specific seed and without replacement
np.random.seed(123)
print(np.random.choice(11, size=5, replace=False))

# Generate a random array of 5 random integers between 0 and 10 (inclusive) with a specific seed and weights
np.random.seed(123)
weights = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1]
print(np.random.choice(11, size=5, p=weights))

# Generate a random array of 5 random integers between 0 and 10 (inclusive) with a specific seed and weights and replace
np.random.seed(123)
weights = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1]
print(np.random.choice(11, size=5, p=weights, replace=True))

# Generate a random array of 5 random integers between 0 and 10 (inclusive) with a specific seed and weights and without replacement
np.random.seed(123)
weights = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1]
print(np.random.choice(11, size=5, p=weights, replace=False))


In [ ]:
# prompt: top 20 numpy methods used in data analysis

# 1. **np.mean()**: Calculate the mean of an array along the specified axis.
# 2. **np.median()**: Calculate the median of an array along the specified axis.
# 3. **np.std()**: Calculate the standard deviation of an array along the specified axis.
# 4. **np.var()**: Calculate the variance of an array along the specified axis.
# 5. **np.max()**: Find the maximum value in an array along the specified axis.
# 6. **np.min()**: Find the minimum value in an array along the specified axis.
# 7. **np.sum()**: Calculate the sum of an array along the specified axis.
# 8. **np.prod()**: Calculate the product of an array along the specified axis.
# 9. **np.cumsum()**: Calculate the cumulative sum of an array along the specified axis.
# 10. **np.diff()**: Calculate the difference between consecutive elements of an array along the specified axis.
# 11. **np.sort()**: Sort an array along the specified axis.
# 12. **np.argsort()**: Return the indices that would sort an array along the specified axis.
# 13. **np.where()**: Return the indices of elements in an array that satisfy a condition.
# 14. **np.unique()**: Return the unique elements of an array.
# 15. **np.in1d()**: Test whether each element of an array is contained in another array.
# 16. **np.setdiff1d()**: Find the elements in one array that are not in another array.
# 17. **np.intersect1d()**: Find the elements that are common to two arrays.
# 18. **np.union1d()**: Find the elements that are in either of two arrays.
# 19. **np.histogram()**: Calculate the histogram of an array.
# 20. **np.corrcoef()**: Calculate the correlation coefficient between two arrays.

In [ ]:
myname="Aditya Kokra"

print(myname)

Aditya Kokra


In [ ]:
import math as m
x=int(input("Enter any number:"))
y=m.sqrt(x)
print(y)